# Generated by Django 3.2.12 on 2022-03-03 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField(verbose_name='Полное оффициальное название')),
                ('ShortName', models.CharField(max_length=20, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Сведения о колледже',
                'verbose_name_plural': 'Сведения о колледже',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CycleCommittees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование цикловой комисии')),
            ],
            options={
                'verbose_name': 'Цикловая комиссия',
                'verbose_name_plural': 'Цикловые комиссии',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование отделения')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='PositionsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ProfModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_main', models.TextField(verbose_name='Наименование основных видов деятельности')),
                ('name_prof', models.TextField(verbose_name='Наименование профессиональных модулей')),
            ],
            options={
                'verbose_name': 'Профессиональный модуль',
                'verbose_name_plural': 'Профессиональные модули',
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование квалификации')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='StudyCycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=40, verbose_name='Индекс')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('Hours', models.PositiveIntegerField(default=0, verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'Учебный цикл',
                'verbose_name_plural': 'Учебные циклы',
            },
        ),
        migrations.CreateModel(
            name='StudyDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=40, verbose_name='Индекс')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('TotalHours', models.PositiveIntegerField(default=0, verbose_name='Всего часов')),
                ('AuditoreHours', models.PositiveIntegerField(default=0, verbose_name='Часов аудиторных всего')),
                ('PracticeHours', models.PositiveIntegerField(default=0, verbose_name='В том числе практических')),
                ('CourseProjectHours', models.PositiveIntegerField(default=0, verbose_name='Курсовой проект')),
                ('ProductionPracticeHours', models.PositiveIntegerField(default=0, verbose_name='Практики')),
                ('IndependentHours', models.PositiveIntegerField(default=0, verbose_name='Самостоятельные')),
                ('Variety', models.BooleanField(default=True, verbose_name='Вариативный')),
                ('Cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.studycycles', verbose_name='Учебный Модуль')),
            ],
            options={
                'verbose_name': 'Учебная дисциплина',
                'verbose_name_plural': 'Учебные дисциплины',
            },
        ),
        migrations.CreateModel(
            name='StudentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=30, verbose_name='Код группы')),
                ('year_of_enrollment', models.DateField(default=datetime.date.today, verbose_name='Год набора')),
                ('base_nine_eleven', models.PositiveIntegerField(default=9, verbose_name='База 9/11 классов')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.department', verbose_name='отделение')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('patronymic', models.TextField(verbose_name='Общество')),
                ('base_roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.roles', verbose_name='Роль в БД')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.positionsinfo', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialities_code', models.CharField(max_length=30, verbose_name='Код специальности')),
                ('name', models.TextField(verbose_name='Наименование специальности')),
                ('cycle_committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.cyclecommittees', verbose_name='цикловая комиссия')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.department', verbose_name='отделение')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('weeks', models.PositiveIntegerField(default=16, verbose_name='Номер')),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.courses', verbose_name='Учебный Курс')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.CreateModel(
            name='QualModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(to='ntkdcs.ProfModules', verbose_name='Модуль')),
                ('qual', models.ManyToManyField(to='ntkdcs.Qualifications', verbose_name='Квалификации')),
            ],
            options={
                'verbose_name': 'Квалификации модули',
                'verbose_name_plural': 'Квалификации модули',
            },
        ),
        migrations.AddField(
            model_name='qualifications',
            name='Spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.specialties', verbose_name='специальности'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='cycle_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.cyclecommittees', verbose_name='цикловая комиссия'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.department', verbose_name='отделение'),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=40, verbose_name='Индекс')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('Cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.studycycles', verbose_name='Учебный Модуль')),
            ],
            options={
                'verbose_name': 'Учебный модуль',
                'verbose_name_plural': 'Учебные модули',
            },
        ),
        migrations.CreateModel(
            name='MDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=40, verbose_name='Индекс')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('TotalHours', models.PositiveIntegerField(default=0, verbose_name='Всего часов')),
                ('AuditoreHours', models.PositiveIntegerField(default=0, verbose_name='Часов аудиторных всего')),
                ('PracticeHours', models.PositiveIntegerField(default=0, verbose_name='В том числе практических')),
                ('CourseProjectHours', models.PositiveIntegerField(default=0, verbose_name='Курсовой проект')),
                ('ProductionPracticeHours', models.PositiveIntegerField(default=0, verbose_name='Практики')),
                ('IndependentHours', models.PositiveIntegerField(default=0, verbose_name='Самостоятельные')),
                ('Variety', models.BooleanField(default=True, verbose_name='Вариативный')),
                ('modules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.modules', verbose_name='Модули')),
            ],
            options={
                'verbose_name': 'МДК',
                'verbose_name_plural': 'МДК',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.roles', verbose_name='Заведующий'),
        ),
        migrations.AddField(
            model_name='cyclecommittees',
            name='chairman',
            field=models.ManyToManyField(related_name='committees_chairmans', to='ntkdcs.Staff', verbose_name='Председатели ЦК'),
        ),
        migrations.AddField(
            model_name='cyclecommittees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntkdcs.department', verbose_name='Отделение'),
        ),
    ]
